### ISSUE TITLE
Detection of missing JavaFX is broken

### ISSUE THREAD

**Issue by Arkanosis** [fthevenet/binjr#27]
… because of the early initialization of logging stuff.

**Comment by fthevenet** [comment]
I'm writing down this here before I forget; removing TextFlowAppender from log4j2.xml and adding it *after* boot time sanity checks should do the trick:
http://logging.apache.org/log4j/2.x/manual/customconfig.html#AddingToCurrent

**Comment by fthevenet** [comment]
Fixed by ea6686f
