### ISSUE TITLE
Improve datetime boundaries handling when max < min

### ISSUE THREAD

**Issue by Arkanosis** [fthevenet/binjr#35]
Currently, when a boundary is changed in a way that causes max < min, an error is displayed.

I think the UX would be much better if instead of raising an error, the other boundary was changed automatically. The main argument is that displaying the error is annoying while doing nothing to solve the issue. I the user had planned to change both the min and the max, changing the other boundary automatically would not make it any more complicated anyway.

The way I see it, the other boundary could be set so that the time frame between min and max is either:
 - the default range (ie. the same as when launching binjr) ;
 - the same as before changing the first boundary (this is how Google Calendar behaves, for example).

I've a slight preference for the latter which seems more natural to me, but as a heavy Google Calendar user, I'm probably biased.

Thanks!

**Comment by fthevenet** [comment]
Already reported in #30

**Comment by fthevenet** [comment]
Done in v1.6.0-SNAPSHOT.
Please review.

**Comment by Arkanosis** [comment]
It looks perfect!

Thanks :)
